# Generated by Django 3.1.6 on 2021-03-03 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_auto_20210302_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='id_poke',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
